// Original Antiyoy sprites (from this repository's assets/, ant skin).
// Generated by devtools/gen-sprites.mjs from
// assets/skins/ant/field_elements/atlas_texture.png + atlas_structure.txt
// (80px "_low" frames, only the ones the web renderer uses).
//
// The atlas and icons are hosted externally (jsDelivr -> this repo) rather
// than embedded, to keep image bytes out of the client artifact. The
// atlas PNG is written to assets/web/atlas.png — commit it alongside this
// file and deploy together so the CDN serves the matching layout.

export const ATLAS_URL = "https://cdn.jsdelivr.net/gh/0verwritten/Antiyoy-Remaster@master/assets/web/atlas.png";

export interface SpriteRect { x: number; y: number; w: number; h: number }

export const SPRITES: Record<string, SpriteRect> = {
  farm1: { x: 0, y: 0, w: 80, h: 80 },
  farm2: { x: 81, y: 0, w: 80, h: 80 },
  farm3: { x: 162, y: 0, w: 80, h: 80 },
  grave: { x: 243, y: 0, w: 80, h: 80 },
  house: { x: 324, y: 0, w: 80, h: 80 },
  man0: { x: 405, y: 0, w: 80, h: 80 },
  man1: { x: 486, y: 0, w: 80, h: 80 },
  man2: { x: 0, y: 81, w: 80, h: 80 },
  man3: { x: 81, y: 81, w: 80, h: 80 },
  palm: { x: 162, y: 81, w: 80, h: 80 },
  pine: { x: 243, y: 81, w: 80, h: 80 },
  strong_tower: { x: 324, y: 81, w: 80, h: 80 },
  tower: { x: 405, y: 81, w: 80, h: 80 },
  castle: { x: 486, y: 81, w: 80, h: 80 },
};

export const ICON_COIN_URL = "https://cdn.jsdelivr.net/gh/0verwritten/Antiyoy-Remaster@master/assets/coin.png";
export const ICON_ENDTURN_URL = "https://cdn.jsdelivr.net/gh/0verwritten/Antiyoy-Remaster@master/assets/end_turn.png";
export const ICON_UNDO_URL = "https://cdn.jsdelivr.net/gh/0verwritten/Antiyoy-Remaster@master/assets/undo.png";
export const ICON_DEFENSE_URL = "https://cdn.jsdelivr.net/gh/0verwritten/Antiyoy-Remaster@master/assets/defense_icon.png";
export const ICON_EXCLAMATION_URL = "https://cdn.jsdelivr.net/gh/0verwritten/Antiyoy-Remaster@master/assets/exclamation_mark.png";

// Original hex tile palette sampled from assets/hex_*.png
export const ORIGINAL_FRACTION_COLORS = [
  "#60b55c", // green (hex_green)
  "#b55c77", // red (hex_red)
  "#735cb5", // purple (hex_blue)
  "#5cb5b0", // cyan (hex_cyan)
  "#b5bc64", // yellow (hex_yellow)
  "#b55dad", // magenta (hex_color5)
  "#cd782e", // orange (hex_color6) — 7th player, campaign only
];
export const ORIGINAL_NEUTRAL_COLOR = "#666666"; // hex_color3
export const WATER_COLOR = "#2a628f"; // game_background_water.png
export const MENU_BACKGROUND_COLOR = "#9b965e"; // main_menu_background.png
