// Converts the original Java campaign level packs into:
//   * web/client/game/__generated__/campaign-index.ts — tiny per-level
//     metadata (name/difficulty/playerCount) for the FIXED levels, kept in
//     the client bundle so the selector renders instantly.
//   * assets/web/campaign-levels.json — the raw level strings, hosted on the
//     CDN (fetched on demand) so the ~110 levels don't bloat the artifact.
//
// Each `case N: return "<level>"` across LevelPack*.java is extracted, parsed
// through the shared codec, and validated by actually loading it in the
// engine (every province must have a town capital and >=2 hexes). Levels that
// can't be represented (fractions 8..10, malformed) are dropped — the
// campaign falls back to a generated map for those indices.
//
// Run from repo root: npx tsx devtools/convert-campaign.ts

import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseLevelString, ScenarioParseError } from "../web/client/game/scenario-codec";
import { createScenarioGame } from "../web/client/game/engine";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const packDir = join(root, "core/src/yio/tro/antiyoy/gameplay/campaign");
const indexOut = join(root, "web/client/game/__generated__/campaign-index.ts");
const jsonOut = join(root, "assets/web/campaign-levels.json");

// Original CampaignProgressManager.INDEX_OF_LAST_LEVEL.
const LAST_LEVEL = 155;

const caseRe = /case\s+(\d+)\s*:\s*return\s+"((?:[^"\\]|\\.)*)"\s*;/g;
const unescapeJava = (s: string) => s.replace(/\\"/g, '"').replace(/\\\\/g, "\\");

// index -> raw level string (first non-"-" wins, matching dispatch order).
const byIndex = new Map<number, string>();
const files = readdirSync(packDir).filter((f) => f.startsWith("LevelPack") && f.endsWith(".java"));
files.sort((a, b) => (a.includes("One") ? -1 : b.includes("One") ? 1 : a.localeCompare(b)));
for (const file of files) {
  const text = readFileSync(join(packDir, file), "utf8");
  let m: RegExpExecArray | null;
  while ((m = caseRe.exec(text)) !== null) {
    const index = Number(m[1]);
    const raw = unescapeJava(m[2]);
    if (raw.trim() === "-" || raw.length < 5) continue;
    if (!byIndex.has(index)) byIndex.set(index, raw);
  }
}

interface Meta {
  level: number;
  name: string;
  difficulty: "easy" | "normal" | "hard";
  playerCount: number;
}

const metas: Meta[] = [];
const rawByLevel: Record<number, string> = {};
const skipped: { level: number; reason: string }[] = [];

for (const [level, raw] of [...byIndex.entries()].sort((a, b) => a[0] - b[0])) {
  if (level < 1 || level > LAST_LEVEL) continue;
  try {
    const scenario = parseLevelString(raw, `campaign-${level}`);
    if (scenario.diplomacy) {
      skipped.push({ level, reason: "diplomacy (deferred)" });
      continue;
    }
    // Validate by loading: every province must be a real one with a capital.
    const state = createScenarioGame(scenario);
    if (state.provinces.length === 0) throw new ScenarioParseError("no provinces after load");
    for (const p of state.provinces) {
      if (state.hexes[p.capital]?.obj !== "town") throw new ScenarioParseError("province without town capital");
      if (p.hexes.length < 2) throw new ScenarioParseError("province with <2 hexes");
    }
    metas.push({ level, name: scenario.name, difficulty: scenario.difficulty ?? "normal", playerCount: scenario.playerCount });
    rawByLevel[level] = raw;
  } catch (err) {
    skipped.push({ level, reason: err instanceof ScenarioParseError ? err.message : String(err) });
  }
}

// Index module (in bundle): metadata only, no raw strings.
const indexLines = [
  "// AUTO-GENERATED by devtools/convert-campaign.ts — do not edit by hand.",
  "// Per-level metadata for FIXED campaign levels (raw strings are hosted on",
  "// the CDN, see campaign-data.ts). Levels not listed here are generated.",
  "",
  "export interface FixedLevelMeta {",
  '  name: string;',
  '  difficulty: "easy" | "normal" | "hard";',
  "  playerCount: number;",
  "}",
  "",
  `export const CAMPAIGN_LEVEL_COUNT = ${LAST_LEVEL};`,
  "",
  "export const FIXED_LEVEL_META: Record<number, FixedLevelMeta> = {",
  ...metas.map(
    (m) => `  ${m.level}: { name: ${JSON.stringify(m.name)}, difficulty: ${JSON.stringify(m.difficulty)}, playerCount: ${m.playerCount} },`
  ),
  "};",
  "",
];
mkdirSync(dirname(indexOut), { recursive: true });
writeFileSync(indexOut, indexLines.join("\n"));

// Hosted JSON (CDN): the raw level strings.
mkdirSync(dirname(jsonOut), { recursive: true });
writeFileSync(jsonOut, JSON.stringify(rawByLevel));

console.log(
  `fixed levels: ${metas.length} -> ${indexOut} (meta) + ${jsonOut} (${(JSON.stringify(rawByLevel).length / 1024).toFixed(1)} KB hosted)`
);
if (skipped.length) {
  console.log(`generated fallback for ${skipped.length} unrepresentable levels:`);
  for (const s of skipped.slice(0, 20)) console.log(`  level ${s.level}: ${s.reason}`);
}
