// Converts the original Java campaign level packs into compact deterministic
// TypeScript data for the web remaster. Reads every
// core/.../campaign/LevelPack*.java, extracts each `case N: return "<level>"`,
// parses it through the shared codec (rejecting anything the web engine cannot
// represent), and writes web/client/game/__generated__/campaign-data.ts.
//
// Run from repo root: npx tsx devtools/convert-campaign.ts

import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseLevelString, ScenarioParseError } from "../web/client/game/scenario-codec";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const packDir = join(root, "core/src/yio/tro/antiyoy/gameplay/campaign");
const outPath = join(root, "web/client/game/__generated__/campaign-data.ts");

// Only the first HARD_LEVELS_START levels are the curated 1..24 campaign;
// convert everything available, the campaign UI decides what to expose.
const MAX_LEVEL = 96;

const caseRe = /case\s+(\d+)\s*:\s*return\s+"((?:[^"\\]|\\.)*)"\s*;/g;

function unescapeJava(s: string): string {
  return s.replace(/\\"/g, '"').replace(/\\\\/g, "\\");
}

// index -> raw level string (first non-"-" wins, matching dispatch order).
const byIndex = new Map<number, string>();
const files = readdirSync(packDir).filter((f) => f.startsWith("LevelPack") && f.endsWith(".java"));
// LevelPackOne is tried first by the factory; keep that priority.
files.sort((a, b) => (a.includes("One") ? -1 : b.includes("One") ? 1 : a.localeCompare(b)));

for (const file of files) {
  const text = readFileSync(join(packDir, file), "utf8");
  let m: RegExpExecArray | null;
  while ((m = caseRe.exec(text)) !== null) {
    const index = Number(m[1]);
    const raw = unescapeJava(m[2]);
    if (raw.trim() === "-" || raw.length < 5) continue;
    if (!byIndex.has(index)) byIndex.set(index, raw);
  }
}

interface Converted {
  level: number;
  name: string;
  raw: string;
  difficulty: "easy" | "normal" | "hard";
  playerCount: number;
}

const converted: Converted[] = [];
const skipped: { level: number; reason: string }[] = [];

for (const [level, raw] of [...byIndex.entries()].sort((a, b) => a[0] - b[0])) {
  if (level < 1 || level > MAX_LEVEL) continue;
  try {
    const scenario = parseLevelString(raw, `campaign-${level}`);
    if (scenario.diplomacy) {
      skipped.push({ level, reason: "diplomacy (deferred)" });
      continue;
    }
    converted.push({
      level,
      name: scenario.name,
      raw,
      difficulty: scenario.difficulty ?? "normal",
      playerCount: scenario.playerCount,
    });
  } catch (err) {
    skipped.push({ level, reason: err instanceof ScenarioParseError ? err.message : String(err) });
  }
}

const lines: string[] = [];
lines.push("// AUTO-GENERATED by devtools/convert-campaign.ts — do not edit by hand.");
lines.push("// Campaign levels as compact legacy strings, parsed at load via the codec.");
lines.push("");
lines.push('import type { CampaignLevelData } from "../scenario-loader";');
lines.push("");
lines.push("export const CAMPAIGN_LEVELS: CampaignLevelData[] = [");
for (const c of converted) {
  lines.push(
    `  { level: ${c.level}, name: ${JSON.stringify(c.name)}, difficulty: ${JSON.stringify(
      c.difficulty
    )}, playerCount: ${c.playerCount}, raw: ${JSON.stringify(c.raw)} },`
  );
}
lines.push("];");
lines.push("");

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, lines.join("\n"));

console.log(`converted ${converted.length} levels -> ${outPath}`);
if (skipped.length) {
  console.log(`skipped ${skipped.length}:`);
  for (const s of skipped.slice(0, 20)) console.log(`  level ${s.level}: ${s.reason}`);
  if (skipped.length > 20) console.log(`  …and ${skipped.length - 20} more`);
}
