// Regenerates web/client/sprites.ts from the original game assets.
// Packs only the frames the web renderer uses, at 80px ("_low" variants),
// to keep the client bundle far below lakebed's 1 MB artifact limit.
// Usage: node devtools/gen-sprites.mjs
import { chromium } from "playwright-core";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const assetDir = join(root, "assets/skins/ant/field_elements");
const spritesPath = join(root, "web/client/sprites.ts");
const hostedDir = join(root, "assets/web");
const atlasOut = join(hostedDir, "atlas.png");

// External asset host: jsDelivr serves repo files with Access-Control-Allow-
// Origin:* so the atlas can be drawn to the canvas without tainting it.
const CDN = "https://cdn.jsdelivr.net/gh/0verwritten/Antiyoy-Remaster@master";
const ATLAS_URL = `${CDN}/assets/web/atlas.png`;
const ICON_COIN_URL = `${CDN}/assets/coin.png`;
const ICON_ENDTURN_URL = `${CDN}/assets/end_turn.png`;
const ICON_UNDO_URL = `${CDN}/assets/undo.png`;

// Frames the web renderer draws (render.ts). "castle" is the province
// capital / main base sprite.
const USED = [
  "farm1", "farm2", "farm3", "grave", "house",
  "man0", "man1", "man2", "man3", "palm", "pine",
  "strong_tower", "tower", "castle",
];
const FRAME = 80; // "_low" frame size
const GUTTER = 1;

// Parse the original atlas structure.
const structure = readFileSync(join(assetDir, "atlas_structure.txt"), "utf8");
const sourceRects = new Map();
for (const line of structure.split("\n")) {
  const m = line.match(/^([a-z_0-9]+)\.png#(\d+) (\d+) (\d+) (\d+)/);
  if (m) sourceRects.set(m[1], { x: +m[2], y: +m[3], w: +m[4], h: +m[5] });
}
for (const name of USED) {
  if (!sourceRects.has(name + "_low")) throw new Error(`missing _low frame: ${name}`);
}

// Target layout: tight grid with a 1px gutter against sampling bleed.
const cols = 7;
const rows = Math.ceil(USED.length / cols);
const outW = cols * (FRAME + GUTTER) - GUTTER;
const outH = rows * (FRAME + GUTTER) - GUTTER;
const placements = USED.map((name, i) => ({
  name,
  src: sourceRects.get(name + "_low"),
  x: (i % cols) * (FRAME + GUTTER),
  y: Math.floor(i / cols) * (FRAME + GUTTER),
}));

const atlasPng = readFileSync(join(assetDir, "atlas_texture.png"));
const atlasDataUrl = "data:image/png;base64," + atlasPng.toString("base64");

const browser = await chromium.launch({ channel: "chrome", headless: true });
const page = await browser.newPage();
const dataUrl = await page.evaluate(
  async ({ atlasDataUrl, placements, outW, outH, FRAME }) => {
    const img = new Image();
    await new Promise((res, rej) => {
      img.onload = res;
      img.onerror = rej;
      img.src = atlasDataUrl;
    });
    const canvas = document.createElement("canvas");
    canvas.width = outW;
    canvas.height = outH;
    const ctx = canvas.getContext("2d");
    for (const p of placements) {
      ctx.drawImage(img, p.src.x, p.src.y, p.src.w, p.src.h, p.x, p.y, FRAME, FRAME);
    }
    return canvas.toDataURL("image/png");
  },
  { atlasDataUrl, placements, outW, outH, FRAME }
);
await browser.close();

// Write the slim atlas PNG to the repo so the CDN can serve it (keeps the
// client bundle free of embedded image bytes).
const pngBase64 = dataUrl.replace(/^data:image\/png;base64,/, "");
mkdirSync(hostedDir, { recursive: true });
writeFileSync(atlasOut, Buffer.from(pngBase64, "base64"));

// Carry the palette block over from the current file (sampled, tiny).
const current = readFileSync(spritesPath, "utf8");
const paletteStart = current.indexOf("// Original hex tile palette");
if (paletteStart < 0) throw new Error("palette block not found");
const paletteBlock = current.slice(paletteStart).trimEnd();

const spriteLines = placements
  .map((p) => `  ${p.name}: { x: ${p.x}, y: ${p.y}, w: ${FRAME}, h: ${FRAME} },`)
  .join("\n");

const out = `// Original Antiyoy sprites (from this repository's assets/, ant skin).
// Generated by devtools/gen-sprites.mjs from
// assets/skins/ant/field_elements/atlas_texture.png + atlas_structure.txt
// (80px "_low" frames, only the ones the web renderer uses).
//
// The atlas and icons are hosted externally (jsDelivr -> this repo) rather
// than embedded, to keep the client artifact under lakebed's 1 MB limit. The
// atlas PNG is written to assets/web/atlas.png — commit it alongside this
// file and deploy together so the CDN serves the matching layout.

export const ATLAS_URL = "${ATLAS_URL}";

export interface SpriteRect { x: number; y: number; w: number; h: number }

export const SPRITES: Record<string, SpriteRect> = {
${spriteLines}
};

export const ICON_COIN_URL = "${ICON_COIN_URL}";
export const ICON_ENDTURN_URL = "${ICON_ENDTURN_URL}";
export const ICON_UNDO_URL = "${ICON_UNDO_URL}";

${paletteBlock}
`;

writeFileSync(spritesPath, out);
console.log(
  `wrote sprites.ts (atlas ${outW}x${outH}, ${placements.length} frames, hosted via CDN) ` +
    `and ${atlasOut} (${(Buffer.from(pngBase64, "base64").length / 1024).toFixed(1)} KB)`
);
